private_keys:
- C:\Users\am\.ssh\id_rsa
- C:\Users\am\.ssh\id_ed25519

hosts:
  example:
    username: David(host的昵称只允许英文和数字和下划线, 不允许使用example或local内置关键字)
    hostname: 127.0.0.1(ip或者域名均可)
    port: 22 #(端口, 默认22, 需要数字)
    keyfile: C:\Example\id_rsa(可选，如果使用密码登录，则不需要)
    password: 1234 #(可选，如果使用密钥登录，则不需要, 建议用密钥登入)
    trash_dir: /home/David/trash #(垃圾桶地址, saferm函数需要)
    protocol: sftp #literal[ftp|sftp] default is sftp.
    buffer_size: 20000000 # default is 20MB
  wsl:
    username: am
    hostname: 172.26.36.83
    port: 22
    password: '1984'
    trash_dir: /home/am/trash

