#:schema ./config.schema.json

[[HOSTS]]
nickname = "example"
protocol = "sftp"
trash_dir = "/home/David/trash"
username = "ls"
buffer_size = 20000000
hostname = "ss"
keyfile = ""
password = "5987"
port = 23


[[HOSTS]]
nickname = "wsl"
hostname = "172.26.36.83"
password = "1984"
port = 22
trash_dir = "/home/am/trash"
username = "am"

[[HOSTS]]
nickname = "ww"
buffer_size = 25165824
hostname = "wws"
keyfile = ""
password = ""
port = 22
protocol = "sftp"
trash_dir = ""
username = "wqwa"

[[HOSTS]]
nickname = "yesh"
buffer_size = 20000000
hostname = "yesh"
keyfile = ""
password = "1234"
port = 22
protocol = "sftp"
trash_dir = "/home/David/trash"
username = "ls"
