[[HOSTS]]
buffer_size = 20000000
hostname = "ss"
keyfile = ""
nickname = "example"
password = "5987"
port = 23
protocol = "sftp"
trash_dir = "/home/David/trash"
username = "ls"

[[HOSTS]]
hostname = "172.26.36.83"
nickname = "wsl"
password = "1984"
port = 22
trash_dir = "/home/am/trash"
username = "am"

[[HOSTS]]
buffer_size = 25165824
hostname = "wws"
keyfile = ""
nickname = "ww"
password = ""
port = 22
protocol = "sftp"
trash_dir = ""
username = "wqwa"

[[HOSTS]]
buffer_size = 20000000
hostname = "yesh"
keyfile = ""
nickname = "yesh"
password = "1234"
port = 22
protocol = "sftp"
trash_dir = "/home/David/trash"
username = "ls"
