CompleteOption:
  maxnum: 5 # negative value means no limit
  complete_delay_ms: 100 # interval max is 1000ms
style: # string to store style of some string
  dir: "[#033415 bold]"
  symlink: "[#033415 bold]"
  regular: "[#033415 bold]"
  otherspecial: "[#033415 bold]"
  username: "[#033415 bold]"
  cwd: "[#033415 bold]"
  number: "[#033415]"
  error: ""
  warning: ""
  success: ""
  info: ""
  debug: ""
  trace: ""
  fatal: ""
  critical: ""
InternalVars:
  local_trash_dir: D:\Document\Desktop\22
  local_default_work_dir: C:\Users\am
