#pragma once
#include "AMCLI/TokenTypeAnalyzer.hpp"
#include <AMBase/Enum.hpp>
#include <atomic>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <functional>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

struct ic_completion_env_s;
using ic_completion_env_t = ic_completion_env_s;

/**
 * @brief Completion target classification used for search-engine routing.
 */
enum class AMCompletionTarget {
  Disabled = 0,
  TopCommand = 1,
  Subcommand = 2,
  LongOption = 3,
  ShortOption = 4,
  VariableName = 5,
  ClientName = 6,
  HostNickname = 7,
  HostAttr = 8,
  TaskId = 9,
  Path = 10,
  VarZone = 11,
};

/**
 * @brief Candidate kind metadata.
 */
enum class AMCompletionKind {
  Module,
  Command,
  Option,
  VariableName,
  VarZone,
  ClientName,
  HostNickname,
  HostAttr,
  TaskId,
  PathLocal,
  PathRemote,
};

/**
 * @brief Completion request source from isocline.
 */
enum class AMCompletionSource {
  Unknown = 0,
  Tab = 1,
  InlineHint = 2,
};

/**
 * @brief Single completion candidate.
 */
struct AMCompletionCandidate {
  std::string insert_text;
  std::string display;
  AMCompletionKind kind = AMCompletionKind::Command;
  std::string help;
  int score = 0;
  std::unordered_map<std::string, std::string> metadata;
  PathType path_type = PathType::Unknown;
};

/**
 * @brief Completion candidate container with response metadata.
 */
struct AMCompletionCandidates {
  std::vector<AMCompletionCandidate> items;
  bool from_cache = false;
};

/**
 * @brief Runtime/completion arguments loaded from settings.
 */
struct AMCompletionArgs {
  int complete_max_items = -1;
  long complete_max_rows = 9;
  bool complete_number_pick = true;
  bool complete_auto_fill = true;
  std::string complete_select_sign;
  std::string complete_order_num_style;
  std::string complete_help_style;
  int complete_delay_ms = 100;
  size_t complete_async_workers = 2;
  std::string input_tag_command;
  std::string input_tag_module;
};

/**
 * @brief Parsed completion context shared with search engines.
 */
struct AMCompletionContext {
  std::string input;
  size_t cursor = 0;
  uint64_t request_id = 0;
  AMCompletionSource source = AMCompletionSource::Unknown;
  std::vector<AMTokenTypeAnalyzer::AMToken> tokens;
  size_t token_index = 0;
  bool has_token = false;
  bool cursor_in_token = false;
  AMTokenTypeAnalyzer::AMToken token;
  std::string token_raw;
  std::string token_text;
  std::string token_prefix_raw;
  std::string token_prefix;
  std::string token_postfix_raw;
  std::string token_postfix;
  bool token_quoted = false;
  std::string module;
  std::string cmd;
  std::vector<std::string> options;
  std::vector<std::string> args;
  std::vector<AMCompletionTarget> targets;
  bool forbid_cache = false;
  const AMCompletionArgs *completion_args = nullptr;
};

class AMCompletionSearchEngine;

/**
 * @brief Async completion result payload returned by background workers.
 */
struct AMCompletionAsyncResult {
  uint64_t request_id = 0;
  AMCompletionTarget target = AMCompletionTarget::Disabled;
  std::vector<AMCompletionCandidate> candidates;
  std::weak_ptr<AMCompletionSearchEngine> source_engine;
};

/**
 * @brief Async completion request generated by search engines.
 */
struct AMCompletionAsyncRequest {
  uint64_t request_id = 0;
  int timeout_ms = 5000;
  AMCompletionTarget target = AMCompletionTarget::Disabled;
  std::function<bool()> interrupt_flag;
  std::function<void()> interrupt_cancel;
  std::weak_ptr<AMCompletionSearchEngine> source_engine;
  std::function<bool(const AMCompletionAsyncRequest &request,
                     AMCompletionAsyncResult *out)>
      search;

  /**
   * @brief Execute the request-specific search routine.
   *
   * @param out Optional result output.
   * @return True when a result is produced.
   */
  bool Search(AMCompletionAsyncResult *out) const;

  /**
   * @brief Return true when the request has been interrupted.
   */
  bool IsInterrupted() const;
};

/**
 * @brief Search collection output for sync + async paths.
 */
struct AMCompletionCollectResult {
  AMCompletionCandidates candidates;
  std::optional<AMCompletionAsyncRequest> async_request;
};

/**
 * @brief Search engine abstraction for pluggable completion providers.
 */
class AMCompletionSearchEngine {
public:
  /**
   * @brief Virtual destructor for polymorphic deletion.
   */
  virtual ~AMCompletionSearchEngine() = default;

  /**
   * @brief Collect completion candidates for a request context.
   *
   * @param ctx Completion request context.
   * @return Candidate payload and optional async request.
   */
  virtual AMCompletionCollectResult
  CollectCandidates(const AMCompletionContext &ctx) = 0;

  /**
   * @brief Sort candidates owned by this search engine.
   *
   * @param ctx Completion request context.
   * @param items Candidate container to sort in-place.
   */
  virtual void SortCandidates(const AMCompletionContext &ctx,
                              std::vector<AMCompletionCandidate> &items) = 0;

  /**
   * @brief Clear internal search-engine cache state.
   */
  virtual void ClearCache();
};

/**
 * @brief Standardized completion request.
 */
struct AMCompletionRequest {
  ic_completion_env_t *cenv = nullptr;
  std::string input;
  size_t cursor = 0;
  uint64_t request_id = 0;
  AMCompletionSource source = AMCompletionSource::Unknown;
};

/**
 * @brief Registration tuple used to bind targets to search engines.
 */
struct AMSearchEngineRegistration {
  std::vector<AMCompletionTarget> targets;
  std::shared_ptr<AMCompletionSearchEngine> engine;
};

/**
 * @brief Build the default completion search-engine registration set.
 */
std::vector<AMSearchEngineRegistration>
AMBuildDefaultSearchEngineRegistrations();

/**
 * @brief Core completion engine that orchestrates parsing, dispatch, and async
 * execution.
 */
class AMCompleteEngine {
public:
  AMCompleteEngine() {
    StartAsyncWorkers_();
    Init();
  }

  /**
   * @brief Register built-in search engines.
   */
  void Init() {
    auto registrations = AMBuildDefaultSearchEngineRegistrations();
    for (const auto &entry : registrations) {
      RegisterSearchEngine(entry.targets, entry.engine);
    }
    EnsurePromptReturnCancelHookRegistered_();
  }

  /**
   * @brief Stop async workers and release resources.
   */
  ~AMCompleteEngine() { StopAsyncWorkers_(); }

  /**
   * @brief Install the completer into isocline.
   */
  void Install();

  /**
   * @brief Clear completion caches managed by registered search engines.
   */
  void ClearCache();

  /**
   * @brief Handle a completion request from isocline.
   *
   * @param cenv Isocline completion environment.
   * @param input Input line.
   * @param cursor Cursor position.
   */
  void HandleCompletion(ic_completion_env_t *cenv, const std::string &input,
                        size_t cursor, AMCompletionSource source);

  /**
   * @brief Load completion configuration from settings.
   */
  void LoadConfig();

  /**
   * @brief Get the current request id.
   */
  uint64_t CurrentRequestId() const;

  /**
   * @brief Register a search engine for one or more completion targets.
   *
   * Each target keeps exactly one engine; later registrations replace earlier
   * bindings for the same target.
   *
   * @param targets Target list routed to this engine.
   * @param engine Search engine instance.
   */
  void
  RegisterSearchEngine(const std::vector<AMCompletionTarget> &targets,
                       const std::shared_ptr<AMCompletionSearchEngine> &engine);

private:
  /**
   * @brief Generate or reuse request ID for the input.
   */
  uint64_t NextRequestId_(const std::string &input, size_t cursor,
                          AMCompletionSource source);

  /**
   * @brief Find the token that owns the cursor.
   */
  bool
  FindTokenAtCursor_(const std::vector<AMTokenTypeAnalyzer::AMToken> &tokens,
                     size_t cursor, AMTokenTypeAnalyzer::AMToken *out,
                     size_t *out_index) const;

  /**
   * @brief Build the completion context for the current input.
   */
  AMCompletionContext BuildContext_(const AMCompletionRequest &request) const;

  /**
   * @brief Dispatch completion requests to registered search engines.
   */
  void DispatchCandidates_(const AMCompletionContext &ctx,
                           AMCompletionCandidates &out);

  /**
   * @brief Emit candidates to isocline with delete ranges.
   */
  void EmitCandidates_(ic_completion_env_t *cenv,
                       const AMCompletionContext &ctx,
                       const AMCompletionCandidates &items);

  /**
   * @brief Start async worker threads.
   */
  void StartAsyncWorkers_();

  /**
   * @brief Stop async worker threads.
   */
  void StopAsyncWorkers_();

  /**
   * @brief Restart async worker threads after config changes.
   */
  void RestartAsyncWorkers_();

  /**
   * @brief Register callback to cancel async completion tasks after each
   * PromptCore return.
   */
  void EnsurePromptReturnCancelHookRegistered_();

  /**
   * @brief Async worker loop body.
   */
  void AsyncWorkerLoop_();

  /**
   * @brief Push an async request into the worker queue.
   */
  void ScheduleAsyncRequest_(AMCompletionAsyncRequest request);

  /**
   * @brief Interrupt and clear queued/inflight async requests.
   */
  void CancelPendingAsyncRequests_();

  /**
   * @brief Consume finished async results for the current context target.
   */
  void ConsumeAsyncResults_(const AMCompletionContext &ctx,
                            AMCompletionCandidates &out);

  /**
   * @brief Resolve the engine for a routed completion target.
   */
  std::shared_ptr<AMCompletionSearchEngine>
  ResolveSearchEngine_(AMCompletionTarget target);

  /**
   * @brief Resolve all registered engines.
   */
  std::vector<std::shared_ptr<AMCompletionSearchEngine>> ResolveAllEngines_();

  AMCompletionArgs args_{};
  std::atomic<uint64_t> request_counter_{0};
  std::atomic<uint64_t> current_request_id_{0};
  std::mutex request_mtx_;
  std::string last_input_;
  size_t last_cursor_ = 0;
  uint64_t last_request_id_ = 0;
  AMCompletionSource last_source_ = AMCompletionSource::Unknown;

  std::mutex engines_mtx_;
  std::unordered_map<AMCompletionTarget,
                     std::shared_ptr<AMCompletionSearchEngine>>
      engines_by_target_;
  std::vector<std::shared_ptr<AMCompletionSearchEngine>> engines_;

  std::atomic<bool> async_stop_{false};
  std::mutex async_queue_mtx_;
  std::condition_variable async_queue_cv_;
  std::deque<AMCompletionAsyncRequest> async_queue_;
  std::vector<std::thread> async_workers_;

  std::mutex async_results_mtx_;
  std::unordered_map<uint64_t, std::vector<AMCompletionAsyncResult>>
      async_results_;

  std::mutex async_interrupts_mtx_;
  std::vector<std::function<void()>> async_interrupts_;

  std::function<void()> prompt_return_cancel_callback_;
  bool prompt_return_cancel_hook_registered_ = false;
};
