"""
Local Filesystem Operations
"""
import AMSFTP.AMData
import AMSFTP.AMEnum
from __future__ import annotations
__all__ = ['BasePathMatch', 'CWD', 'FormatTime', 'HomePath', 'IsAbs', 'PathMatch', 'UnifyPathSep', 'abspath', 'basename', 'dirname', 'extname', 'getsize', 'iwalk', 'listdir', 'mkdirs', 'split', 'split_basename', 'stat', 'walk']
class BasePathMatch:
    """
    Base Path Match Class
    """
    def find(self, path: str, type: AMSFTP.AMEnum.SearchType = ...) -> list[AMSFTP.AMData.PathInfo]:
        ...
    def name_match(self, name: str, pattern: str) -> bool:
        ...
    def str_match(self, name: str, pattern: str) -> bool:
        ...
    def walk_match(self, parts: list[str], match_parts: list[str]) -> bool:
        ...
class PathMatch(BasePathMatch):
    """
    Path Match Class
    """
    def __init__(self) -> None:
        ...
def CWD() -> str:
    ...
def FormatTime(time: int, format: str = '%Y-%m-%d %H:%M:%S') -> str:
    ...
def HomePath() -> str:
    ...
def IsAbs(path: str, sep: str = '') -> bool:
    ...
def UnifyPathSep(path: str, sep: str = '') -> str:
    ...
def abspath(path: str, parsing_home: bool = True, home: str = '', cwd: str = '', sep: str = '') -> str:
    ...
def basename(path: str) -> str:
    ...
def dirname(path: str) -> str:
    ...
def extname(path: str) -> str:
    ...
def getsize(path: str, trace_link: bool = False) -> int:
    ...
def iwalk(path: str, ignore_sepcial_file: bool = True) -> list[AMSFTP.AMData.PathInfo]:
    ...
def listdir(path: str) -> list[AMSFTP.AMData.PathInfo]:
    ...
def mkdirs(path: str) -> str:
    ...
def split(path: str) -> list[str]:
    """
    return list[str], the path is split by separator
    """
def split_basename(basename: str) -> tuple[str, str]:
    """
    return tuple[str, str], the first is the basename without extension, the second is the extension(no .)
    """
def stat(path: str, trace_link: bool = False) -> tuple[str, AMSFTP.AMData.PathInfo]:
    ...
def walk(path: str, max_depth: int = -1, ignore_sepcial_file: bool = True) -> list[tuple[list[str], list[AMSFTP.AMData.PathInfo]]]:
    ...
