import AMSFTP
from __future__ import annotations
import typing
__all__ = ['basename', 'dirname', 'getsize', 'listdir', 'mkdirs', 'realpath', 'stat', 'walk']
def basename(path: str) -> str:
    ...
def dirname(path: str) -> str:
    ...
def getsize(path: str, trace_link: bool = False) -> int:
    ...
def listdir(path: str) -> list[AMSFTP.PathInfo]:
    ...
def mkdirs(path: str) -> tuple[AMSFTP.ErrorCode, str]:
    ...
def realpath(path: str) -> str:
    ...
def stat(path: str, trace_link: bool = False) -> AMSFTP.PathInfo | tuple[AMSFTP.ErrorCode, str]:
    ...
def walk(path: str, ignore_sepcial_file: bool = True, trace_link: bool = False) -> list[AMSFTP.PathInfo]:
    ...
