import AMSFTP
from __future__ import annotations
import typing
__all__ = ['basename', 'dirname', 'mkdirs', 'realpath', 'stat', 'walk']
def basename(path: str) -> str:
    ...
def dirname(path: str) -> str:
    ...
def mkdirs(path: str) -> bool:
    ...
def realpath(path: str) -> str:
    ...
def stat(path: str) -> AMSFTP.PathInfo | tuple[AMSFTP.ErrorCode, str]:
    ...
def walk(path: str, ignore_sepcial_file: bool = True) -> list[AMSFTP.PathInfo]:
    ...
