#pragma once
#include <cstdint>

namespace AMInterface::style {
enum class StyleIndex : uint8_t {
  None = 0,
  Protocol,
  Abort,
  Common,
  Module,
  Command,
  IllegalCommand,
  Option,
  String,
  PublicVarname,
  PrivateVarname,
  VarnameZone,
  NonexistentVarname,
  VarValue,
  Nickname,
  DisconnectedNickname,
  UnestablishedNickname,
  NonexistentNickname,
  ValidNewNickname,
  InvalidNewNickname,
  TerminalName,
  DisconnectedTerminalName,
  UnestablishedTerminalName,
  NonexistentTerminalName,
  ChannelName,
  DisconnectedChannelName,
  NonexistentChannelName,
  ValidNewChannelName,
  InvalidNewChannelName,
  BuiltinArg,
  NonexistentBuiltinArg,
  Username,
  AtSign,
  TermnameAtSign,
  DollarSign,
  EqualSign,
  LeftBraceSign,
  RightBraceSign,
  ColonSign,
  EscapedSign,
  BangSign,
  ShellCmd,
  Cwd,
  Number,
  Timestamp,
  PathLike,
  FindPattern,
  TableSkeleton,
  Error
};
} // namespace AMInterface::style
