#pragma once
#include <cstdint>

namespace AMInterface::style {
enum class StyleIndex : uint8_t {
  None = 0,
  Protocol,
  Abort,
  Common,
  Module,
  Command,
  IllegalCommand,
  Option,
  String,
  PublicVarname,
  PrivateVarname,
  VarnameZone,
  NonexistentVarname,
  VarValue,
  Nickname,
  DisconnectedNickname,
  UnestablishedNickname,
  NonexistentNickname,
  ValidNewNickname,
  InvalidNewNickname,
  TerminalName,
  DisconnectedTerminalName,
  NonexistentTerminalName,
  ValidNewTerminalName,
  InvalidNewTerminalName,
  TermClientNameOK,
  TermClientNameDisconnected,
  TermClientNameUnestablished,
  TermClientNameNonexistent,
  BuiltinArg,
  NonexistentBuiltinArg,
  Username,
  AtSign,
  TermnameAtSign,
  DollarSign,
  EqualSign,
  LeftBraceSign,
  RightBraceSign,
  ColonSign,
  EscapedSign,
  BangSign,
  ShellCmd,
  Cwd,
  Number,
  Timestamp,
  PathLike,
  FindPattern,
  TableSkeleton,
  Error,
  ValidValue,
  InvalidValue,
};
} // namespace AMInterface::style
